### ISSUE TITLE
Review contributor journey

### ISSUE THREAD

**Issue by ibagha** [concourse/dutyfree#112]
https://miro.com/app/board/o9J_kwGZZ7U=/

- [ ] Possibility of usability testing the workflow

**Comment by YoussB** [comment]
The current contributor workflow looks as follows:
- contributor forks the dutyfree repo.
- They add their resource (to either a separate file or recources.yml)
- They create a pull request against the repo
- maybe: a pipeline validates the resource (dockerhub pullable and runable)
- Concourse maintainers to accept the pull request
- after the PR is merged in, a pipeline pushes the new resource into the dutyfree db (using either a cli tool or the server's api).
- Since the server reads directly from the db, that will result into an instantaneous update for dutyfree.

**Comment by YoussB** [comment]
stories: #139 #140 #141 will be capturing in more details the design and development of the above workflow.
